//! Saved Apps: persistent, relaunchable generative-UI widgets.
//!
//! A *saved app* owns one widget HTML blob and one opaque JSON state blob.
//! The HTML can be regenerated by the model on demand ("make the buttons
//! bigger") while the JSON state rides across untouched, so user data (e.g.
//! fitness tracker entries) survives UI rewrites.
//!
//! Persistence layout directly under `{directory}`:
//! - `saved_apps.json`      — `SavedAppsSnapshot` index (metadata only)
//! - `html/{app_id}.html`   — current widget HTML, one per app
//! - `state/{app_id}.json`  — one `SavedAppState` per app
//!
//! The caller supplies the final absolute path; this module does not
//! append any subdirectory of its own.
//!
//! Splitting HTML and state into separate files means state survives HTML
//! rewrites atomically, and later cloud-sync wiring can move each at its
//! own cadence.
//!
//! Mirrors `preferences.rs`: JSON file, atomic tmp+rename, dedicated
//! `APPS_WRITE_LOCK` (separate from `preferences.rs`'s `WRITE_LOCK`),
//! corrupt-file recovery to defaults.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::Mutex;

use serde::{Deserialize, Serialize};
use uuid::Uuid;

const INDEX_FILE: &str = "saved_apps.json";
const HTML_DIR: &str = "html";
const STATE_DIR: &str = "state";
const CURRENT_VERSION: u32 = 1;
const TITLE_MAX_CHARS: usize = 120;
const DEFAULT_TITLE: &str = "Saved App";
const STATE_BYTES_MAX: usize = 256 * 1024;

static APPS_WRITE_LOCK: Mutex<()> = Mutex::new(());

// ── Public types ────────────────────────────────────────────────────────

/// Persistent handle for a generative-UI widget that survived across one
/// or more HTML rewrites.
///
/// Two identity fields:
/// - `id`: stable UUIDv4 used as the disk filename (`html/{id}.html`,
///   `state/{id}.json`) and the primary key for all post-promotion
///   operations (rename, replace_html, delete, save_state, load_state).
/// - `app_id`: model-chosen slug (e.g. `"fitness-tracker"`) used as a
///   composite-key identity *together with* `origin_thread_id`. Reusing
///   the same slug within the same thread updates the existing app;
///   picking a fresh slug creates a new one. Slugs are NOT unique across
///   threads — `fitness-tracker` in thread A and in thread B are
///   independent apps with distinct UUIDs.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, uniffi::Record)]
pub struct SavedApp {
    pub id: String,
    /// Model-facing identity. Slug (lowercase, hyphen-separated). Unique
    /// only within a given `origin_thread_id`.
    #[serde(default)]
    pub app_id: String,
    pub title: String,
    pub width: f64,
    pub height: f64,
    pub schema_version: u32,
    pub created_at_ms: i64,
    pub updated_at_ms: i64,
    pub origin_thread_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, uniffi::Record)]
pub struct SavedAppWithPayload {
    pub app: SavedApp,
    pub widget_html: String,
    pub state_json: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, uniffi::Record)]
pub struct SavedAppsSnapshot {
    pub apps: Vec<SavedApp>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, uniffi::Record)]
pub struct SavedAppState {
    pub app_id: String,
    pub state_json: String,
    pub schema_version: u32,
    pub updated_at_ms: i64,
}

#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum SavedAppError {
    #[error("Saved app not found: {0}")]
    NotFound(String),
    #[error("State payload exceeds 256 KB cap ({0} bytes)")]
    StateTooLarge(u64),
    #[error("Invalid state JSON: {0}")]
    InvalidStateJson(String),
    #[error("I/O error: {0}")]
    Io(String),
}

// ── Persisted wire shapes ───────────────────────────────────────────────

#[derive(Serialize, Deserialize)]
struct PersistedIndex {
    version: u32,
    #[serde(default)]
    apps: Vec<SavedApp>,
}

impl From<&SavedAppsSnapshot> for PersistedIndex {
    fn from(snap: &SavedAppsSnapshot) -> Self {
        Self {
            version: CURRENT_VERSION,
            apps: snap.apps.clone(),
        }
    }
}

impl From<PersistedIndex> for SavedAppsSnapshot {
    fn from(p: PersistedIndex) -> Self {
        Self { apps: p.apps }
    }
}

#[derive(Serialize, Deserialize)]
struct PersistedState {
    version: u32,
    app_id: String,
    state_json: String,
    schema_version: u32,
    updated_at_ms: i64,
}

impl From<&SavedAppState> for PersistedState {
    fn from(s: &SavedAppState) -> Self {
        Self {
            version: CURRENT_VERSION,
            app_id: s.app_id.clone(),
            state_json: s.state_json.clone(),
            schema_version: s.schema_version,
            updated_at_ms: s.updated_at_ms,
        }
    }
}

impl From<PersistedState> for SavedAppState {
    fn from(p: PersistedState) -> Self {
        Self {
            app_id: p.app_id,
            state_json: p.state_json,
            schema_version: p.schema_version,
            updated_at_ms: p.updated_at_ms,
        }
    }
}

// ── Path helpers ────────────────────────────────────────────────────────

fn apps_root(directory: &str) -> PathBuf {
    PathBuf::from(directory)
}

fn index_path(directory: &str) -> PathBuf {
    apps_root(directory).join(INDEX_FILE)
}

fn html_path(directory: &str, app_id: &str) -> PathBuf {
    apps_root(directory)
        .join(HTML_DIR)
        .join(format!("{app_id}.html"))
}

fn state_path(directory: &str, app_id: &str) -> PathBuf {
    apps_root(directory)
        .join(STATE_DIR)
        .join(format!("{app_id}.json"))
}

// ── Atomic read/write helpers ───────────────────────────────────────────

fn read_index(path: &Path) -> SavedAppsSnapshot {
    let bytes = match fs::read(path) {
        Ok(b) => b,
        Err(_) => return SavedAppsSnapshot { apps: Vec::new() },
    };
    match serde_json::from_slice::<PersistedIndex>(&bytes) {
        Ok(persisted) => persisted.into(),
        Err(_) => SavedAppsSnapshot { apps: Vec::new() },
    }
}

fn write_index(path: &Path, value: &SavedAppsSnapshot) -> Result<(), SavedAppError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| SavedAppError::Io(e.to_string()))?;
    }
    let persisted: PersistedIndex = value.into();
    let json = serde_json::to_vec_pretty(&persisted)
        .map_err(|e| SavedAppError::Io(format!("serialize: {e}")))?;
    write_atomic(path, &json, "json.tmp")
}

fn write_atomic(path: &Path, bytes: &[u8], tmp_ext: &str) -> Result<(), SavedAppError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| SavedAppError::Io(e.to_string()))?;
    }
    let tmp_path = path.with_extension(tmp_ext);
    {
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .open(&tmp_path)
            .map_err(|e| SavedAppError::Io(e.to_string()))?;
        if let Err(e) = file.write_all(bytes) {
            let _ = fs::remove_file(&tmp_path);
            return Err(SavedAppError::Io(e.to_string()));
        }
        let _ = file.sync_all();
    }
    if let Err(e) = fs::rename(&tmp_path, path) {
        let _ = fs::remove_file(&tmp_path);
        return Err(SavedAppError::Io(e.to_string()));
    }
    Ok(())
}

fn read_html(directory: &str, app_id: &str) -> Option<String> {
    fs::read_to_string(html_path(directory, app_id)).ok()
}

fn write_html(directory: &str, app_id: &str, html: &str) -> Result<(), SavedAppError> {
    let path = html_path(directory, app_id);
    write_atomic(&path, html.as_bytes(), "html.tmp")
}

fn read_state(directory: &str, app_id: &str) -> Option<SavedAppState> {
    let path = state_path(directory, app_id);
    let bytes = fs::read(&path).ok()?;
    match serde_json::from_slice::<PersistedState>(&bytes) {
        Ok(persisted) => Some(persisted.into()),
        Err(_) => None,
    }
}

fn write_state(directory: &str, value: &SavedAppState) -> Result<(), SavedAppError> {
    let path = state_path(directory, &value.app_id);
    let persisted: PersistedState = value.into();
    let json = serde_json::to_vec_pretty(&persisted)
        .map_err(|e| SavedAppError::Io(format!("serialize: {e}")))?;
    write_atomic(&path, &json, "json.tmp")
}

// ── Helpers ─────────────────────────────────────────────────────────────

fn now_ms() -> i64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

fn sanitize_title(raw: &str) -> String {
    let stripped: String = raw
        .chars()
        .filter(|c| !c.is_control())
        .collect::<String>()
        .trim()
        .to_string();
    let clamped: String = stripped.chars().take(TITLE_MAX_CHARS).collect();
    if clamped.is_empty() {
        DEFAULT_TITLE.to_string()
    } else {
        clamped
    }
}

fn clamp_dimension(value: f64, fallback: f64) -> f64 {
    if value.is_finite() && value > 0.0 {
        value
    } else {
        fallback
    }
}

fn acquire_write_guard() -> std::sync::MutexGuard<'static, ()> {
    APPS_WRITE_LOCK
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner)
}

/// Broadcast `AppStoreUpdateRecord::SavedAppsChanged` on the shared
/// reducer so platforms know to refresh their `SavedAppsStore`. No-op
/// when the MobileClient singleton hasn't been initialized yet (tests
/// that drive `saved_apps_*` in isolation).
///
/// Intentionally called AFTER the `APPS_WRITE_LOCK` is released — the
/// reducer has its own broadcast channel and subscribers reload on
/// their own schedulers; holding the disk-write lock across a fan-out
/// would only add contention.
fn notify_saved_apps_changed() {
    if let Some(client) = crate::ffi::shared::shared_mobile_client_if_initialized() {
        client.app_store.emit_saved_apps_changed();
    }
}

// ── Slug helpers ────────────────────────────────────────────────────────

const SLUG_MAX_CHARS: usize = 32;

/// Normalize `raw` into a URL-safe slug: lowercase, alphanumerics
/// preserved, runs of anything else collapsed to a single `-`, leading
/// and trailing `-` trimmed, clamped to `SLUG_MAX_CHARS`.
fn derive_slug_from_title(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len());
    let mut last_was_dash = true;
    for c in raw.chars() {
        if c.is_ascii_alphanumeric() {
            out.extend(c.to_lowercase());
            last_was_dash = false;
        } else if !last_was_dash {
            out.push('-');
            last_was_dash = true;
        }
    }
    let trimmed = out.trim_matches('-').to_string();
    let clamped: String = trimmed.chars().take(SLUG_MAX_CHARS).collect();
    let clamped = clamped.trim_end_matches('-').to_string();
    if clamped.is_empty() {
        "app".to_string()
    } else {
        clamped
    }
}

/// Given a base slug, pick the lowest-index suffix (`base`, `base-2`,
/// `base-3`, …) that is not already taken by another saved app in the
/// same `origin_thread_id`. `exclude_uuid` lets an in-place update skip
/// matching against itself.
fn disambiguate_slug(
    base: &str,
    origin_thread_id: Option<&str>,
    apps: &[SavedApp],
    exclude_uuid: Option<&str>,
) -> String {
    let conflicts = |candidate: &str| -> bool {
        apps.iter().any(|existing| {
            existing.origin_thread_id.as_deref() == origin_thread_id
                && existing.app_id == candidate
                && Some(existing.id.as_str()) != exclude_uuid
        })
    };
    if !conflicts(base) {
        return base.to_string();
    }
    for n in 2u32.. {
        let candidate = format!("{base}-{n}");
        if !conflicts(&candidate) {
            return candidate;
        }
    }
    // Unreachable: u32::MAX apps with the same slug is not a real concern.
    format!("{base}-x")
}

/// Fill in missing `app_id` slugs on the index in-memory. Used after
/// reading the index whenever we're about to act on the data. Does NOT
/// write back — the next mutation's write picks up the migrated values.
fn migrate_missing_slugs(index: &mut SavedAppsSnapshot) {
    // Build a map of (thread_id, slug) already taken so we disambiguate
    // against existing non-empty slugs as well as each other.
    let need_migration: Vec<usize> = index
        .apps
        .iter()
        .enumerate()
        .filter_map(|(i, app)| app.app_id.is_empty().then_some(i))
        .collect();
    if need_migration.is_empty() {
        return;
    }
    // Two-pass: derive candidate slugs, then disambiguate each against
    // the working apps list (which grows as we assign).
    for i in need_migration {
        let base = derive_slug_from_title(&index.apps[i].title);
        // We need the origin_thread_id + a fresh look at the apps list
        // minus the entry being migrated, so clone the thread id out.
        let thread = index.apps[i].origin_thread_id.clone();
        let self_uuid = index.apps[i].id.clone();
        let slug = disambiguate_slug(&base, thread.as_deref(), &index.apps, Some(&self_uuid));
        index.apps[i].app_id = slug;
    }
}

// ── Public API (UniFFI) ─────────────────────────────────────────────────

/// List all saved apps, newest-updated first. Apps with missing `app_id`
/// slugs (from before R2) are migrated in memory — the migrated slug
/// gets persisted on the next mutation.
#[uniffi::export]
pub fn saved_apps_list(directory: String) -> SavedAppsSnapshot {
    let _guard = acquire_write_guard();
    let mut snapshot = read_index(&index_path(&directory));
    migrate_missing_slugs(&mut snapshot);
    snapshot
        .apps
        .sort_by(|a, b| b.updated_at_ms.cmp(&a.updated_at_ms));
    snapshot
}

/// Return all saved apps whose `origin_thread_id` matches `thread_id`,
/// newest-updated first. Used by the thread-start/resume developer
/// instructions seeder and by platforms that want to surface the
/// per-thread context hint.
#[uniffi::export]
pub fn saved_apps_for_thread(directory: String, thread_id: String) -> Vec<SavedApp> {
    let _guard = acquire_write_guard();
    let mut snapshot = read_index(&index_path(&directory));
    migrate_missing_slugs(&mut snapshot);
    let mut matched: Vec<SavedApp> = snapshot
        .apps
        .into_iter()
        .filter(|app| app.origin_thread_id.as_deref() == Some(thread_id.as_str()))
        .collect();
    matched.sort_by(|a, b| b.updated_at_ms.cmp(&a.updated_at_ms));
    matched
}

/// Fetch a saved app's metadata + HTML + (optional) state for display.
/// Returns `None` if the app ID is unknown or the HTML file is missing.
#[uniffi::export]
pub fn saved_app_get(directory: String, app_id: String) -> Option<SavedAppWithPayload> {
    let _guard = acquire_write_guard();
    let index = read_index(&index_path(&directory));
    let app = index.apps.into_iter().find(|app| app.id == app_id)?;
    let widget_html = read_html(&directory, &app_id)?;
    let state = read_state(&directory, &app_id);
    Some(SavedAppWithPayload {
        app,
        widget_html,
        state_json: state.map(|s| s.state_json),
    })
}

/// Composite-key upsert: identity is `(origin_thread_id, app_id)`.
///
/// - If a saved app with that exact pair exists, update its HTML +
///   dimensions + title (if non-empty) + `schema_version`, bump
///   `updated_at_ms`, and leave `state_json` untouched.
/// - Otherwise, create a fresh `SavedApp` with a new UUIDv4 `id`.
///
/// Titles are sanitized; an empty incoming title on an existing app
/// leaves the stored title unchanged. This is the auto-save path used
/// by the `show_widget` finalize hook in `conversation.rs`. Returns the
/// upserted (or inserted) app.
#[uniffi::export]
pub fn saved_app_upsert(
    directory: String,
    origin_thread_id: String,
    app_id: String,
    title: String,
    widget_html: String,
    width: f64,
    height: f64,
    schema_version: u32,
) -> Result<SavedApp, SavedAppError> {
    let result = (|| -> Result<SavedApp, SavedAppError> {
        let _guard = acquire_write_guard();
        let slug = derive_slug_from_title(&app_id);
        let now = now_ms();
        let sanitized_title = sanitize_title(&title);
        let width = clamp_dimension(width, 800.0);
        let height = clamp_dimension(height, 600.0);

        let index_path = index_path(&directory);
        let mut index = read_index(&index_path);
        migrate_missing_slugs(&mut index);

        let existing_idx = index.apps.iter().position(|app| {
            app.origin_thread_id.as_deref() == Some(origin_thread_id.as_str()) && app.app_id == slug
        });

        if let Some(i) = existing_idx {
            // Update path: rewrite HTML file on disk with the new content,
            // then commit the index. State file is preserved.
            let uuid = index.apps[i].id.clone();
            write_html(&directory, &uuid, &widget_html)?;

            let app = &mut index.apps[i];
            app.width = width;
            app.height = height;
            app.schema_version = schema_version;
            app.updated_at_ms = now;
            // Only overwrite title when the model actually provided
            // one. `sanitize_title` returns `DEFAULT_TITLE` for empty
            // input, so detect "empty input" from the raw incoming
            // string.
            if !title.trim().is_empty() {
                app.title = sanitized_title;
            }
            let updated = app.clone();
            write_index(&index_path, &index)?;
            Ok(updated)
        } else {
            // Insert path. Disambiguate only across slugs already in
            // this thread — legitimate callers reusing the exact slug
            // are handled by the `existing_idx` branch above, so any
            // collision here means two concurrent sibling slugs.
            let final_slug =
                disambiguate_slug(&slug, Some(origin_thread_id.as_str()), &index.apps, None);
            let uuid = Uuid::new_v4().to_string();
            let title_final = if title.trim().is_empty() {
                // Fall back to something readable from the slug rather
                // than the literal "Saved App" default.
                readable_title_from_slug(&final_slug)
            } else {
                sanitized_title
            };
            let app = SavedApp {
                id: uuid.clone(),
                app_id: final_slug,
                title: title_final,
                width,
                height,
                schema_version,
                created_at_ms: now,
                updated_at_ms: now,
                origin_thread_id: Some(origin_thread_id),
            };
            write_html(&directory, &uuid, &widget_html)?;
            index.apps.push(app.clone());
            if let Err(e) = write_index(&index_path, &index) {
                let _ = fs::remove_file(html_path(&directory, &uuid));
                return Err(e);
            }
            Ok(app)
        }
    })();
    if result.is_ok() {
        notify_saved_apps_changed();
    }
    result
}

fn readable_title_from_slug(slug: &str) -> String {
    let mut out = String::new();
    let mut capitalize_next = true;
    for c in slug.chars() {
        if c == '-' {
            out.push(' ');
            capitalize_next = true;
        } else if capitalize_next {
            out.extend(c.to_uppercase());
            capitalize_next = false;
        } else {
            out.push(c);
        }
    }
    if out.trim().is_empty() {
        DEFAULT_TITLE.to_string()
    } else {
        out
    }
}

/// Promote an ephemeral widget into a saved app.
///
/// **Prefer `saved_app_upsert`** when the caller has a model-chosen slug
/// (the `show_widget` auto-save path). `saved_app_promote` exists for the
/// legacy manual Save-as-App entry point and for callers that don't
/// know/care about slugs; it derives a slug from the title internally.
#[uniffi::export]
pub fn saved_app_promote(
    directory: String,
    title: String,
    widget_html: String,
    width: f64,
    height: f64,
    origin_thread_id: Option<String>,
) -> Result<SavedApp, SavedAppError> {
    let result = (|| -> Result<SavedApp, SavedAppError> {
        let _guard = acquire_write_guard();
        let id = Uuid::new_v4().to_string();
        let now = now_ms();
        let sanitized_title = sanitize_title(&title);

        let index_path = index_path(&directory);
        let mut index = read_index(&index_path);
        migrate_missing_slugs(&mut index);

        let slug = disambiguate_slug(
            &derive_slug_from_title(&sanitized_title),
            origin_thread_id.as_deref(),
            &index.apps,
            None,
        );

        let app = SavedApp {
            id: id.clone(),
            app_id: slug,
            title: sanitized_title,
            width: clamp_dimension(width, 800.0),
            height: clamp_dimension(height, 600.0),
            schema_version: 1,
            created_at_ms: now,
            updated_at_ms: now,
            origin_thread_id,
        };

        write_html(&directory, &id, &widget_html)?;

        index.apps.push(app.clone());
        if let Err(e) = write_index(&index_path, &index) {
            // Roll back the HTML file so we don't leak orphan files on disk.
            let _ = fs::remove_file(html_path(&directory, &id));
            return Err(e);
        }
        Ok(app)
    })();
    if result.is_ok() {
        notify_saved_apps_changed();
    }
    result
}

/// Update a saved app's title. Clamps/sanitizes the title; does not
/// change the `updated_at_ms` (a rename is not a content update).
#[uniffi::export]
pub fn saved_app_rename(
    directory: String,
    app_id: String,
    title: String,
) -> Result<SavedApp, SavedAppError> {
    let result = (|| -> Result<SavedApp, SavedAppError> {
        let _guard = acquire_write_guard();
        let index_path = index_path(&directory);
        let mut index = read_index(&index_path);
        migrate_missing_slugs(&mut index);
        let sanitized = sanitize_title(&title);
        let mut updated: Option<SavedApp> = None;
        for app in index.apps.iter_mut() {
            if app.id == app_id {
                app.title = sanitized.clone();
                updated = Some(app.clone());
                break;
            }
        }
        match updated {
            Some(app) => {
                write_index(&index_path, &index)?;
                Ok(app)
            }
            None => Err(SavedAppError::NotFound(app_id)),
        }
    })();
    if result.is_ok() {
        notify_saved_apps_changed();
    }
    result
}

/// Replace the saved app's widget HTML. Bumps `updated_at_ms`.
#[uniffi::export]
pub fn saved_app_replace_html(
    directory: String,
    app_id: String,
    widget_html: String,
    width: f64,
    height: f64,
) -> Result<SavedApp, SavedAppError> {
    let result = (|| -> Result<SavedApp, SavedAppError> {
        let _guard = acquire_write_guard();
        let index_path = index_path(&directory);
        let mut index = read_index(&index_path);
        migrate_missing_slugs(&mut index);
        let now = now_ms();
        let mut updated: Option<SavedApp> = None;
        for app in index.apps.iter_mut() {
            if app.id == app_id {
                app.width = clamp_dimension(width, app.width);
                app.height = clamp_dimension(height, app.height);
                app.updated_at_ms = now;
                updated = Some(app.clone());
                break;
            }
        }
        let Some(app) = updated else {
            return Err(SavedAppError::NotFound(app_id));
        };

        // Write the new HTML *before* committing the index, so a crash
        // between steps leaves the app unchanged rather than pointing
        // at missing content.
        write_html(&directory, &app_id, &widget_html)?;
        write_index(&index_path, &index)?;
        Ok(app)
    })();
    if result.is_ok() {
        notify_saved_apps_changed();
    }
    result
}

/// Delete the saved app and cascade to its HTML + state files.
#[uniffi::export]
pub fn saved_app_delete(directory: String, app_id: String) -> Result<(), SavedAppError> {
    let mut actually_deleted = false;
    let result = (|| -> Result<(), SavedAppError> {
        let _guard = acquire_write_guard();
        let index_path = index_path(&directory);
        let mut index = read_index(&index_path);
        migrate_missing_slugs(&mut index);
        let before = index.apps.len();
        index.apps.retain(|app| app.id != app_id);
        if index.apps.len() == before {
            // Idempotent: deleting a missing app is a no-op. No
            // broadcast — listeners have nothing to reload.
            return Ok(());
        }
        write_index(&index_path, &index)?;
        let _ = fs::remove_file(html_path(&directory, &app_id));
        let _ = fs::remove_file(state_path(&directory, &app_id));
        actually_deleted = true;
        Ok(())
    })();
    if result.is_ok() && actually_deleted {
        notify_saved_apps_changed();
    }
    result
}

/// Persist the app's JSON state blob. Validates payload is valid JSON
/// and enforces the 256 KB cap. Updates the app's `schema_version` on
/// the index.
#[uniffi::export]
pub fn saved_app_save_state(
    directory: String,
    app_id: String,
    state_json: String,
    schema_version: u32,
) -> Result<SavedAppState, SavedAppError> {
    if state_json.len() > STATE_BYTES_MAX {
        return Err(SavedAppError::StateTooLarge(state_json.len() as u64));
    }
    if let Err(e) = serde_json::from_str::<serde_json::Value>(&state_json) {
        return Err(SavedAppError::InvalidStateJson(e.to_string()));
    }
    let result = (|| -> Result<SavedAppState, SavedAppError> {
        let _guard = acquire_write_guard();

        let index_path = index_path(&directory);
        let mut index = read_index(&index_path);
        migrate_missing_slugs(&mut index);
        let app_exists = index.apps.iter_mut().any(|app| {
            if app.id == app_id {
                app.schema_version = schema_version;
                app.updated_at_ms = now_ms();
                true
            } else {
                false
            }
        });
        if !app_exists {
            return Err(SavedAppError::NotFound(app_id));
        }
        write_index(&index_path, &index)?;

        let state = SavedAppState {
            app_id: app_id.clone(),
            state_json,
            schema_version,
            updated_at_ms: now_ms(),
        };
        write_state(&directory, &state)?;
        Ok(state)
    })();
    if result.is_ok() {
        notify_saved_apps_changed();
    }
    result
}

/// Load a saved app's persisted state, if any.
#[uniffi::export]
pub fn saved_app_load_state(directory: String, app_id: String) -> Option<SavedAppState> {
    let _guard = acquire_write_guard();
    read_state(&directory, &app_id)
}

// ── Internal helpers consumed by `AppClient::update_saved_app` ──────────

/// Short-form description of a state blob for the model: top-level keys
/// + a single compact example value each. Returns `None` when no state
/// file exists. Designed for seeding an update prompt; never exposes the
/// raw user data in full.
pub(crate) fn abbreviated_state_shape(directory: &str, app_id: &str) -> Option<String> {
    let state = read_state(directory, app_id)?;
    let value: serde_json::Value = serde_json::from_str(&state.state_json).ok()?;
    let obj = value.as_object()?;
    let mut lines = Vec::with_capacity(obj.len());
    for (key, val) in obj.iter() {
        let sample = match val {
            serde_json::Value::Array(items) => {
                let first = items
                    .first()
                    .map(|item| truncate(&item.to_string(), 120))
                    .unwrap_or_else(|| "[]".into());
                format!("[{}, ... ({} items)]", first, items.len())
            }
            serde_json::Value::Object(_) => {
                format!("{{...}}")
            }
            serde_json::Value::String(s) => format!("{:?}", truncate(s, 120)),
            other => truncate(&other.to_string(), 120),
        };
        lines.push(format!("  \"{key}\": {sample}"));
    }
    Some(lines.join(",\n"))
}

fn truncate(value: &str, max: usize) -> String {
    if value.len() <= max {
        return value.to_string();
    }
    let mut end = max;
    while end > 0 && !value.is_char_boundary(end) {
        end -= 1;
    }
    format!("{}…", &value[..end])
}

// ── Tests ───────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use std::thread;
    use tempfile::tempdir;

    fn dir(t: &tempfile::TempDir) -> String {
        t.path().to_string_lossy().into()
    }

    fn promote_sample(directory: &str, title: &str) -> SavedApp {
        saved_app_promote(
            directory.into(),
            title.into(),
            "<div>hello</div>".into(),
            800.0,
            600.0,
            Some("thread-xyz".into()),
        )
        .expect("promote")
    }

    #[test]
    fn list_empty_when_missing() {
        let t = tempdir().unwrap();
        let snap = saved_apps_list(dir(&t));
        assert!(snap.apps.is_empty());
    }

    #[test]
    fn promote_round_trip_with_payload() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        let promoted = promote_sample(&d, "Fit Tracker");
        assert_eq!(promoted.title, "Fit Tracker");
        assert_eq!(promoted.width, 800.0);

        let listed = saved_apps_list(d.clone()).apps;
        assert_eq!(listed.len(), 1);
        assert_eq!(listed[0].id, promoted.id);

        let fetched = saved_app_get(d.clone(), promoted.id.clone()).expect("get");
        assert_eq!(fetched.widget_html, "<div>hello</div>");
        assert!(fetched.state_json.is_none());
    }

    #[test]
    fn get_returns_none_when_html_missing() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        let app = promote_sample(&d, "X");
        // Manually delete HTML to simulate lost-disk edge case described
        // in the plan.
        std::fs::remove_file(html_path(&d, &app.id)).unwrap();
        assert!(saved_app_get(d, app.id).is_none());
    }

    #[test]
    fn corrupt_index_recovers_to_empty() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        std::fs::create_dir_all(apps_root(&d)).unwrap();
        std::fs::write(index_path(&d), b"{ not valid json").unwrap();

        let snap = saved_apps_list(d);
        assert!(snap.apps.is_empty());
    }

    #[test]
    fn corrupt_state_returns_none_not_error() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        let app = promote_sample(&d, "X");
        std::fs::create_dir_all(apps_root(&d).join(STATE_DIR)).unwrap();
        std::fs::write(state_path(&d, &app.id), b"{ definitely not json").unwrap();

        assert!(saved_app_load_state(d, app.id).is_none());
    }

    #[test]
    fn save_state_rejects_oversized_payload() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        let app = promote_sample(&d, "X");
        let giant = format!(r#""{}""#, "a".repeat(STATE_BYTES_MAX + 1));
        let err = saved_app_save_state(d, app.id, giant, 1).unwrap_err();
        assert!(matches!(err, SavedAppError::StateTooLarge(_)));
    }

    #[test]
    fn save_state_rejects_invalid_json() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        let app = promote_sample(&d, "X");
        let err = saved_app_save_state(d, app.id, "not json".into(), 1).unwrap_err();
        assert!(matches!(err, SavedAppError::InvalidStateJson(_)));
    }

    #[test]
    fn save_state_round_trip_updates_schema_version() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        let app = promote_sample(&d, "X");
        let state = saved_app_save_state(
            d.clone(),
            app.id.clone(),
            r#"{"entries":[1,2,3]}"#.into(),
            2,
        )
        .unwrap();
        assert_eq!(state.schema_version, 2);

        let loaded = saved_app_load_state(d.clone(), app.id.clone()).unwrap();
        assert_eq!(loaded.state_json, r#"{"entries":[1,2,3]}"#);

        let reloaded_app = saved_apps_list(d).apps.into_iter().next().unwrap();
        assert_eq!(reloaded_app.schema_version, 2);
    }

    #[test]
    fn concurrent_saves_serialize_cleanly() {
        let t = tempdir().unwrap();
        let d = Arc::new(dir(&t));
        let app = promote_sample(&d, "Concurrent");
        let app_id = Arc::new(app.id);

        let mut handles = Vec::new();
        for i in 0..16 {
            let d = Arc::clone(&d);
            let app_id = Arc::clone(&app_id);
            handles.push(thread::spawn(move || {
                let payload = format!(r#"{{"counter":{i}}}"#);
                saved_app_save_state((*d).clone(), (*app_id).clone(), payload, 1)
                    .expect("concurrent save");
            }));
        }
        for h in handles {
            h.join().unwrap();
        }
        let final_state = saved_app_load_state((*d).clone(), (*app_id).clone()).unwrap();
        // One of the writers wins; just verify the file is well-formed
        // and parses as a small JSON object with a counter field.
        let parsed: serde_json::Value = serde_json::from_str(&final_state.state_json).unwrap();
        assert!(parsed.get("counter").is_some());
    }

    #[test]
    fn rename_sanitizes_and_persists() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        let app = promote_sample(&d, "Orig");

        let long = "z".repeat(500);
        let with_control = format!("hello\x07world");
        let renamed = saved_app_rename(d.clone(), app.id.clone(), with_control).unwrap();
        assert_eq!(renamed.title, "helloworld");

        let renamed = saved_app_rename(d.clone(), app.id.clone(), long).unwrap();
        assert_eq!(renamed.title.chars().count(), TITLE_MAX_CHARS);

        let empty = saved_app_rename(d.clone(), app.id.clone(), "   ".into()).unwrap();
        assert_eq!(empty.title, DEFAULT_TITLE);

        let listed = saved_apps_list(d).apps;
        assert_eq!(listed[0].title, DEFAULT_TITLE);
    }

    #[test]
    fn rename_missing_returns_not_found() {
        let t = tempdir().unwrap();
        let err = saved_app_rename(dir(&t), "nope".into(), "New".into()).unwrap_err();
        assert!(matches!(err, SavedAppError::NotFound(_)));
    }

    #[test]
    fn replace_html_updates_content_and_mtime() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        let app = promote_sample(&d, "X");
        let original_mtime = app.updated_at_ms;

        // sleep a tick so the mtime actually moves
        std::thread::sleep(std::time::Duration::from_millis(5));

        let replaced = saved_app_replace_html(
            d.clone(),
            app.id.clone(),
            "<span>new</span>".into(),
            900.0,
            700.0,
        )
        .unwrap();
        assert!(replaced.updated_at_ms >= original_mtime);
        assert_eq!(replaced.width, 900.0);

        let fetched = saved_app_get(d, app.id).unwrap();
        assert_eq!(fetched.widget_html, "<span>new</span>");
    }

    #[test]
    fn delete_cascades_html_and_state() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        let app = promote_sample(&d, "X");
        saved_app_save_state(d.clone(), app.id.clone(), r#"{"a":1}"#.into(), 1).unwrap();

        assert!(html_path(&d, &app.id).exists());
        assert!(state_path(&d, &app.id).exists());

        saved_app_delete(d.clone(), app.id.clone()).unwrap();

        assert!(!html_path(&d, &app.id).exists());
        assert!(!state_path(&d, &app.id).exists());
        assert!(saved_apps_list(d).apps.is_empty());
    }

    #[test]
    fn delete_is_idempotent() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        // Deleting with no index file should succeed silently.
        saved_app_delete(d.clone(), "phantom".into()).unwrap();
        // Same after an index exists but the id doesn't.
        let _ = promote_sample(&d, "X");
        saved_app_delete(d, "phantom".into()).unwrap();
    }

    #[test]
    fn abbreviated_state_shape_summarizes() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        let app = promote_sample(&d, "X");
        let state_json =
            r#"{"entries":[{"id":1,"v":"run"},{"id":2,"v":"walk"}],"units":"imperial"}"#;
        saved_app_save_state(d.clone(), app.id.clone(), state_json.into(), 2).unwrap();
        let summary = abbreviated_state_shape(&d, &app.id).unwrap();
        assert!(summary.contains("entries"));
        assert!(summary.contains("units"));
        assert!(summary.contains("2 items"));
    }

    // ── R2: slug / thread-scoped identity ─────────────────────────────

    fn upsert_sample(
        directory: &str,
        thread: &str,
        slug: &str,
        title: &str,
        html: &str,
    ) -> SavedApp {
        saved_app_upsert(
            directory.into(),
            thread.into(),
            slug.into(),
            title.into(),
            html.into(),
            800.0,
            600.0,
            1,
        )
        .expect("upsert")
    }

    #[test]
    fn derive_slug_from_title_is_stable_and_safe() {
        assert_eq!(derive_slug_from_title("Fitness Tracker"), "fitness-tracker");
        assert_eq!(derive_slug_from_title("Todo List!!"), "todo-list");
        assert_eq!(derive_slug_from_title("  Budget 2025  "), "budget-2025");
        assert_eq!(derive_slug_from_title("---"), "app");
        assert_eq!(derive_slug_from_title(""), "app");
        let long = "a".repeat(200);
        assert!(derive_slug_from_title(&long).chars().count() <= SLUG_MAX_CHARS);
    }

    #[test]
    fn upsert_creates_new_app_when_slug_unused() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        let app = upsert_sample(&d, "thread-a", "fitness-tracker", "Fit", "<div>v1</div>");
        assert_eq!(app.app_id, "fitness-tracker");
        assert_eq!(app.origin_thread_id.as_deref(), Some("thread-a"));
        assert_eq!(app.title, "Fit");

        // Disk reflects it.
        let listed = saved_apps_list(d.clone()).apps;
        assert_eq!(listed.len(), 1);
        assert_eq!(listed[0].id, app.id);
        assert!(
            std::fs::read_to_string(html_path(&d, &app.id))
                .unwrap()
                .contains("v1")
        );
    }

    #[test]
    fn upsert_updates_existing_when_slug_matches_thread() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        let first = upsert_sample(&d, "thread-a", "fitness-tracker", "Fit", "<div>v1</div>");

        // Save state so we can assert it survives the HTML rewrite.
        saved_app_save_state(
            d.clone(),
            first.id.clone(),
            r#"{"entries":[1,2,3]}"#.into(),
            2,
        )
        .unwrap();

        // Upsert again with the same (thread, slug).
        let second = upsert_sample(
            &d,
            "thread-a",
            "fitness-tracker",
            "Fit Pro",
            "<div>v2</div>",
        );

        assert_eq!(second.id, first.id, "same UUID, in-place update");
        assert_eq!(second.title, "Fit Pro");
        assert_eq!(second.app_id, "fitness-tracker");

        // HTML is now v2.
        let fetched = saved_app_get(d.clone(), second.id.clone()).unwrap();
        assert!(fetched.widget_html.contains("v2"));

        // State survived.
        let state = saved_app_load_state(d.clone(), second.id.clone()).unwrap();
        assert_eq!(state.state_json, r#"{"entries":[1,2,3]}"#);

        // Still exactly one app on disk.
        assert_eq!(saved_apps_list(d).apps.len(), 1);
    }

    #[test]
    fn upsert_same_slug_different_threads_creates_two_apps() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        let a = upsert_sample(&d, "thread-a", "fitness-tracker", "Fit A", "<div>A</div>");
        let b = upsert_sample(&d, "thread-b", "fitness-tracker", "Fit B", "<div>B</div>");

        assert_ne!(a.id, b.id);
        assert_eq!(a.app_id, b.app_id, "same slug is fine across threads");

        let listed = saved_apps_list(d).apps;
        assert_eq!(listed.len(), 2);
        let titles: Vec<_> = listed.iter().map(|app| app.title.clone()).collect();
        assert!(titles.contains(&"Fit A".to_string()));
        assert!(titles.contains(&"Fit B".to_string()));
    }

    #[test]
    fn upsert_empty_title_uses_readable_fallback_from_slug() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        let app = upsert_sample(&d, "thread-a", "fitness-tracker", "", "<div>v1</div>");
        assert_eq!(app.title, "Fitness Tracker");
    }

    #[test]
    fn upsert_empty_title_on_existing_app_leaves_title_intact() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        let first = upsert_sample(&d, "thread-a", "fitness-tracker", "My Fit", "<div>v1</div>");
        let second = upsert_sample(&d, "thread-a", "fitness-tracker", "", "<div>v2</div>");
        assert_eq!(second.id, first.id);
        assert_eq!(second.title, "My Fit");
    }

    #[test]
    fn saved_apps_for_thread_filters_correctly() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        upsert_sample(&d, "thread-a", "fit", "Fit", "<div>A</div>");
        upsert_sample(&d, "thread-a", "todo", "Todo", "<div>B</div>");
        upsert_sample(&d, "thread-b", "fit", "Other Fit", "<div>C</div>");

        let a_apps = saved_apps_for_thread(d.clone(), "thread-a".into());
        assert_eq!(a_apps.len(), 2);
        let a_slugs: std::collections::HashSet<_> =
            a_apps.iter().map(|app| app.app_id.clone()).collect();
        assert!(a_slugs.contains("fit"));
        assert!(a_slugs.contains("todo"));

        let b_apps = saved_apps_for_thread(d.clone(), "thread-b".into());
        assert_eq!(b_apps.len(), 1);
        assert_eq!(b_apps[0].title, "Other Fit");

        let c_apps = saved_apps_for_thread(d, "thread-missing".into());
        assert!(c_apps.is_empty());
    }

    #[test]
    fn legacy_migration_derives_slug_from_title() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        // Seed a legacy index with no `app_id` fields.
        std::fs::create_dir_all(apps_root(&d)).unwrap();
        std::fs::write(
            index_path(&d),
            br#"{
              "version": 1,
              "apps": [
                {
                  "id": "uuid-legacy-1",
                  "title": "Fitness Tracker",
                  "width": 800, "height": 600,
                  "schema_version": 1,
                  "created_at_ms": 1, "updated_at_ms": 1,
                  "origin_thread_id": "thread-x"
                }
              ]
            }"#,
        )
        .unwrap();

        let apps = saved_apps_list(d.clone()).apps;
        assert_eq!(apps.len(), 1);
        assert_eq!(apps[0].app_id, "fitness-tracker");
        assert_eq!(apps[0].id, "uuid-legacy-1");
    }

    #[test]
    fn legacy_migration_disambiguates_collision_within_thread() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        std::fs::create_dir_all(apps_root(&d)).unwrap();
        // Two legacy apps in the same thread with identical titles.
        std::fs::write(
            index_path(&d),
            br#"{
              "version": 1,
              "apps": [
                { "id": "u1", "title": "Notes", "width": 800, "height": 600,
                  "schema_version": 1, "created_at_ms": 1, "updated_at_ms": 2,
                  "origin_thread_id": "t1" },
                { "id": "u2", "title": "Notes", "width": 800, "height": 600,
                  "schema_version": 1, "created_at_ms": 1, "updated_at_ms": 3,
                  "origin_thread_id": "t1" },
                { "id": "u3", "title": "Notes", "width": 800, "height": 600,
                  "schema_version": 1, "created_at_ms": 1, "updated_at_ms": 4,
                  "origin_thread_id": "t2" }
              ]
            }"#,
        )
        .unwrap();

        let apps = saved_apps_list(d.clone()).apps;
        // t1 gets `notes` and `notes-2`, t2 keeps `notes` (different thread).
        let t1: std::collections::HashSet<_> = apps
            .iter()
            .filter(|a| a.origin_thread_id.as_deref() == Some("t1"))
            .map(|a| a.app_id.clone())
            .collect();
        assert!(t1.contains("notes"));
        assert!(t1.contains("notes-2"));
        assert_eq!(t1.len(), 2);

        let t2_slug = apps
            .iter()
            .find(|a| a.origin_thread_id.as_deref() == Some("t2"))
            .map(|a| a.app_id.clone())
            .unwrap();
        assert_eq!(t2_slug, "notes");
    }

    #[test]
    fn legacy_migration_persists_on_next_mutation() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        std::fs::create_dir_all(apps_root(&d)).unwrap();
        std::fs::write(
            index_path(&d),
            br#"{
              "version": 1,
              "apps": [
                { "id": "u1", "title": "Widget Thing", "width": 800, "height": 600,
                  "schema_version": 1, "created_at_ms": 1, "updated_at_ms": 1,
                  "origin_thread_id": "t1" }
              ]
            }"#,
        )
        .unwrap();

        // Trigger a mutation so migrated slugs get written back.
        let _ = saved_app_rename(d.clone(), "u1".into(), "Widget Thing".into()).unwrap();

        let raw = std::fs::read_to_string(index_path(&d)).unwrap();
        assert!(raw.contains("widget-thing"), "raw index: {raw}");
    }

    #[test]
    fn upsert_disambiguates_when_slug_collides_with_legacy_migrated_entry() {
        let t = tempdir().unwrap();
        let d = dir(&t);
        std::fs::create_dir_all(apps_root(&d)).unwrap();
        // Legacy entry whose derived slug is "notes".
        std::fs::write(
            index_path(&d),
            br#"{
              "version": 1,
              "apps": [
                { "id": "u-legacy", "title": "Notes", "width": 800, "height": 600,
                  "schema_version": 1, "created_at_ms": 1, "updated_at_ms": 1,
                  "origin_thread_id": "t1" }
              ]
            }"#,
        )
        .unwrap();

        // Model-driven auto-save with slug="notes" on the same thread,
        // but a different logical app (different UUID). Plan says this
        // should be treated as a *new* app because the composite key
        // doesn't match a previously model-named app — here it does
        // match the migrated legacy entry, so we update in place.
        let first = upsert_sample(&d, "t1", "notes", "Other Notes", "<div>v1</div>");
        assert_eq!(
            first.id, "u-legacy",
            "should match the migrated legacy entry via composite key"
        );

        // A truly new slug creates a distinct app.
        let second = upsert_sample(&d, "t1", "tasks", "Tasks", "<div>v1</div>");
        assert_ne!(second.id, first.id);
    }
}
